/**
 * The values a consumer's *test suite* needs, in a form a test runner can actually load.
 *
 * `testing/index.js` gives consumers the DOM contract. That is enough to find things in a page
 * and not enough to write a meaningful test against them. Anyone verifying a real deployment has
 * to drive a session that clears the claim engine's gates first — otherwise every "nothing
 * leaked", "nothing persisted", "nothing changed after exposure" assertion is satisfied by a
 * Mirror that concluded nothing, and the suite reports that the invariants hold on a page where
 * they were never exercised.
 *
 * Driving such a session requires the thresholds (how long is long enough, how many passages is
 * enough) and the manifest (which passages exist, how long they are, what they are about). Both
 * live in `.ts`, which the host application's bundler compiles happily and a test runner does
 * not: Node refuses to strip types under `node_modules`, and Playwright hardcodes the same
 * exclusion.
 *
 * So this shape is emitted to `testing/reference.json`, alongside the DOM contract, for the same
 * reason and with the same audience. It is generated rather than hand-maintained, and
 * `test/reference.test.ts` rebuilds it in memory and compares — the idiom already used for
 * `src/ruleset.digest.json` and `src/generated/source-spans.ts`. A threshold change that did not
 * regenerate the file fails the build here rather than silently disqualifying a downstream
 * consumer's reading script months later.
 *
 * It is deliberately *derived*, never authoritative. `src/thresholds.ts` and `src/manifest.ts`
 * remain the only definitions; this is a projection of them.
 */

import { PASSAGE_MANIFEST_VERSION, passageManifest } from "../src/manifest";
import { THRESHOLDS } from "../src/thresholds";
import { PACKAGE_VERSION, RULESET_VERSION } from "../src/version";
import { inferenceRules } from "../src/claims";

export interface MirrorReference {
  readonly why: string;
  readonly packageVersion: string;
  readonly rulesetVersion: string;
  readonly passageManifestVersion: string;
  readonly thresholds: typeof THRESHOLDS;
  readonly passages: readonly {
    readonly id: string;
    readonly label: string;
    readonly section: string;
    readonly wordCount: number;
    readonly categories: readonly string[];
  }[];
  /** Rule ids and their confidence ceilings, so a consumer can assert on rules by name. */
  readonly rules: readonly {
    readonly id: string;
    readonly promotable: boolean;
    readonly maximumConfidence: string;
  }[];
}

export function buildReference(): MirrorReference {
  return {
    why:
      "Generated by tools/generate-reference.ts from src/thresholds.ts, src/manifest.ts and " +
      "src/claims.ts. Do not edit. This exists so a consumer's test runner can read the values " +
      "without loading TypeScript out of node_modules; the .ts files remain authoritative.",
    packageVersion: PACKAGE_VERSION,
    rulesetVersion: RULESET_VERSION,
    passageManifestVersion: PASSAGE_MANIFEST_VERSION,
    thresholds: THRESHOLDS,
    passages: passageManifest.passages.map((passage) => ({
      id: passage.id,
      label: passage.label,
      section: passage.section,
      wordCount: passage.wordCount,
      categories: [...passage.categories],
    })),
    rules: inferenceRules.map((rule) => ({
      id: rule.id,
      promotable: rule.promotable,
      maximumConfidence: rule.maximumConfidence,
    })),
  };
}

export function serializeReference(reference: MirrorReference): string {
  return `${JSON.stringify(reference, null, 2)}\n`;
}
